export const GET_USERS = {
  PENDING: "GET_USERS_PENDING",
  SUCCESS: "GET_USERS_SUCCESS",
  FAILED: "GET_USERS_FAILED",
};

export const CREATE_USER = {
  PENDING: "CREATE_USER_PENDING",
  SUCCESS: "CREATE_USER_SUCCESS",
  FAILED: "CREATE_USER_FAILED",
};

export const UPDATE_USER = {
  PENDING: "UPDATE_USER_PENDING",
  SUCCESS: "UPDATE_USER_SUCCESS",
  FAILED: "UPDATE_USER_FAILED",
};

export const DELETE_USER = {
  PENDING: "DELETE_USER_PENDING",
  SUCCESS: "DELETE_USER_SUCCESS",
  FAILED: "DELETE_USER_FAILED",
};
